language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install .[server]
# command to run tests
script:
  - python -m pylint --rcfile .pylintrc ./google_images_download
  - python -m flake8
  - pytest -m 'not no_travis'
